const SCRIPT='loadstring(game:HttpGet("https://awh.filho.wtf/full.lua"))()';
function copyScript(){navigator.clipboard.writeText(SCRIPT).then(()=>{const l=document.getElementById('copyLabel');if(l){l.textContent='Copied!';setTimeout(()=>l.textContent='Copy loadstring',2000)}})}
document.querySelectorAll('#faqList details').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)document.querySelectorAll('#faqList details').forEach(o=>{if(o!==d)o.open=false})}));
const API='/api/reviews';let selectedScore=0,reviewsCache=[],currentUser=null;
function escapeHtml(s){return String(s).replace(/&/g,'&').replace(/</g,'<').replace(/>/g,'>').replace(/"/g,'"')}
function myReview(){if(!currentUser)return null;return reviewsCache.find(r=>r.username===currentUser.username)||null}
function showAuthTab(tab){const login=document.getElementById('loginForm'),signup=document.getElementById('signupForm');const tL=document.getElementById('tabLogin'),tS=document.getElementById('tabSignup');document.getElementById('authMsg')?.classList.add('hidden');if(tab==='login'){login.classList.remove('hidden');signup.classList.add('hidden');tL.classList.add('active');tS.classList.remove('active')}else{signup.classList.remove('hidden');login.classList.add('hidden');tS.classList.add('active');tL.classList.remove('active')}}
function setFormFromReview(r){if(!r){selectedScore=0;if(document.getElementById('revText'))document.getElementById('revText').value='';document.querySelectorAll('.score-btn').forEach(x=>x.classList.remove('border-violet-500','bg-violet-500/20','text-violet-200'));const lab=document.getElementById('submitLabel');if(lab)lab.textContent='Submit rating';document.getElementById('deleteMyRev')?.classList.add('hidden');return}selectedScore=Number(r.score)||0;if(document.getElementById('revText'))document.getElementById('revText').value=r.text||'';document.querySelectorAll('.score-btn').forEach(x=>{x.classList.remove('border-violet-500','bg-violet-500/20','text-violet-200');if(Number(x.textContent)===selectedScore)x.classList.add('border-violet-500','bg-violet-500/20','text-violet-200')});const lab=document.getElementById('submitLabel');if(lab)lab.textContent='Update my review';document.getElementById('deleteMyRev')?.classList.remove('hidden')}
function updateAuthUI(){const out=document.getElementById('loggedOut'),inn=document.getElementById('loggedIn'),nav=document.getElementById('navAuthBtn');if(currentUser){out?.classList.add('hidden');inn?.classList.remove('hidden');const nm=document.getElementById('userName'),av=document.getElementById('userAvatar');if(nm)nm.textContent=currentUser.username;if(av)av.textContent=(currentUser.username||'?')[0].toUpperCase();if(nav){nav.textContent=currentUser.username;nav.href='#reviews'}}else{out?.classList.remove('hidden');inn?.classList.add('hidden');if(nav){nav.textContent='Sign in';nav.href='#reviews'}}}
async function loadUser(){try{const r=await fetch('/api/auth/me',{credentials:'include',cache:'no-store'});const data=await r.json();currentUser=data.user||null}catch{currentUser=null}updateAuthUI()}
async function fetchReviews(){try{const r=await fetch(API+'?t='+Date.now(),{cache:'no-store'});const data=await r.json();if(Array.isArray(data.reviews)){reviewsCache=data.reviews;return reviewsCache}}catch(e){}return reviewsCache}
async function postReview(review){const r=await fetch(API,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(review)});const data=await r.json().catch(()=>({}));if(r.status===401)throw new Error('Please log in first');if(!r.ok)throw new Error(data.error||'Failed');if(Array.isArray(data.reviews))reviewsCache=data.reviews;return reviewsCache}
async function deleteReview(id){const r=await fetch(API+'?id='+encodeURIComponent(id),{method:'DELETE',credentials:'include'});const data=await r.json().catch(()=>({}));if(r.status===401)throw new Error('Please log in first');if(!r.ok)throw new Error(data.error||'Failed to delete');if(Array.isArray(data.reviews))reviewsCache=data.reviews;return reviewsCache}
function renderReviews(list){list=list||reviewsCache;const avgLabel=document.getElementById('avgLabel'),avgStars=document.getElementById('avgStars'),revList=document.getElementById('revList');if(!avgLabel||!revList)return;if(!list.length){avgLabel.textContent='0 ratings · out of 10';avgStars.textContent='☆☆☆☆☆';revList.innerHTML='<p class="text-center text-zinc-600 text-xs py-2">No reviews yet — be the first.</p>';if(currentUser)setFormFromReview(null);return}const avg=list.reduce((s,r)=>s+Number(r.score),0)/list.length;avgLabel.textContent=list.length+' rating'+(list.length===1?'':'s')+' · '+avg.toFixed(1)+' / 10';let stars='';for(let i=1;i<=5;i++)stars+=(avg/2>=i-0.25)?'★':'☆';avgStars.textContent=stars;if(currentUser)setFormFromReview(myReview());revList.innerHTML=list.slice().reverse().map(r=>{const date=r.date?new Date(r.date).toLocaleDateString():'';const isMine=currentUser&&r.username===currentUser.username;const initial=(r.username||'?')[0].toUpperCase();const avatar='<div class="w-8 h-8 rounded-full bg-violet-500/30 flex items-center justify-center text-xs font-bold shrink-0">'+escapeHtml(initial)+'</div>';const actions=isMine?'<div class="flex gap-2 shrink-0"><button type="button" class="text-xs text-violet-400 hover:text-violet-300" data-edit="'+escapeHtml(r.id||'')+'">Edit</button><button type="button" class="text-xs text-zinc-600 hover:text-red-400" data-del="'+escapeHtml(r.id||'')+'">Delete</button></div>':'';return '<div class="glass p-4 rounded-xl'+(isMine?' ring-1 ring-violet-500/30':'')+'"><div class="flex items-start justify-between gap-2 mb-1"><div class="flex items-center gap-2 min-w-0">'+avatar+'<div class="min-w-0"><span class="font-semibold text-sm">'+escapeHtml(r.username||'Anonymous')+(isMine?' <span class="text-[10px] text-violet-400">(you)</span>':'')+'</span><span class="text-yellow-400 text-xs ml-2">'+('★'.repeat(Math.min(5,Math.ceil(r.score/2))))+('☆'.repeat(5-Math.min(5,Math.ceil(r.score/2))))+'</span><span class="text-zinc-500 text-xs ml-1">'+r.score+'/10</span></div></div>'+actions+'</div>'+(r.text?'<p class="text-zinc-400 text-sm mt-1">'+escapeHtml(r.text)+'</p>':'')+(date?'<p class="text-zinc-600 text-[11px] mt-1">'+date+'</p>':'')+'</div>'}).join('');revList.querySelectorAll('[data-del]').forEach(btn=>{btn.onclick=async()=>{if(!confirm('Delete your review?'))return;try{await deleteReview(btn.getAttribute('data-del'));setFormFromReview(null);renderReviews(reviewsCache)}catch(e){alert(e.message)}}});revList.querySelectorAll('[data-edit]').forEach(btn=>{btn.onclick=()=>{const r=reviewsCache.find(x=>x.id===btn.getAttribute('data-edit'));if(r){setFormFromReview(r);document.getElementById('authBox')?.scrollIntoView({behavior:'smooth',block:'center'})}}})}
function buildScoreBtns(){const sb=document.getElementById('scoreBtns');if(!sb||sb.children.length)return;for(let i=1;i<=10;i++){const b=document.createElement('button');b.type='button';b.textContent=i;b.className='py-2 rounded-xl bg-black/40 border border-white/10 text-sm hover:border-violet-500 score-btn';b.onclick=()=>{selectedScore=i;sb.querySelectorAll('.score-btn').forEach(x=>x.classList.remove('border-violet-500','bg-violet-500/20','text-violet-200'));b.classList.add('border-violet-500','bg-violet-500/20','text-violet-200')};sb.appendChild(b)}}
function showAuthMsg(text,ok){const m=document.getElementById('authMsg');if(!m)return;m.className='text-center text-sm '+(ok?'text-emerald-400':'text-amber-400');m.textContent=text;m.classList.remove('hidden')}
document.getElementById('signupBtn')?.addEventListener('click',async()=>{const username=(document.getElementById('signupUser')?.value||'').trim();const password=document.getElementById('signupPass')?.value||'';const password2=document.getElementById('signupPass2')?.value||'';if(username.length<3){showAuthMsg('Username must be at least 3 characters');return}if(!/^[a-zA-Z0-9_]+$/.test(username)){showAuthMsg('Username: letters, numbers, underscore only');return}if(password.length<6){showAuthMsg('Password must be at least 6 characters');return}if(password!==password2){showAuthMsg('Passwords do not match');return}const btn=document.getElementById('signupBtn');if(btn){btn.disabled=true;btn.style.opacity='0.6'}try{const r=await fetch('/api/auth/signup',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Sign up failed');currentUser=data.user;updateAuthUI();showAuthMsg('Account created — you are logged in',true);await fetchReviews();renderReviews(reviewsCache)}catch(e){showAuthMsg(e.message)}if(btn){btn.disabled=false;btn.style.opacity='1'}});
document.getElementById('loginBtn')?.addEventListener('click',async()=>{const username=(document.getElementById('loginUser')?.value||'').trim();const password=document.getElementById('loginPass')?.value||'';if(!username||!password){showAuthMsg('Enter username and password');return}const btn=document.getElementById('loginBtn');if(btn){btn.disabled=true;btn.style.opacity='0.6'}try{const r=await fetch('/api/auth/login',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Login failed');currentUser=data.user;updateAuthUI();await fetchReviews();renderReviews(reviewsCache)}catch(e){showAuthMsg(e.message)}if(btn){btn.disabled=false;btn.style.opacity='1'}});
document.getElementById('logoutBtn')?.addEventListener('click',async()=>{await fetch('/api/auth/logout',{credentials:'include'});currentUser=null;updateAuthUI();setFormFromReview(null);renderReviews(reviewsCache)});
document.getElementById('submitRev')?.addEventListener('click',async()=>{const msg=document.getElementById('revMsg');if(!currentUser){msg.className='text-center text-sm text-amber-400';msg.textContent='Please log in first';msg.classList.remove('hidden');return}if(!selectedScore){msg.className='text-center text-sm text-amber-400';msg.textContent='Pick a score from 1–10 first';msg.classList.remove('hidden');return}const text=(document.getElementById('revText')?.value||'').trim().slice(0,400);const existing=myReview();const review={id:existing?existing.id:('r_'+Date.now()),score:selectedScore,text,date:new Date().toISOString()};const btn=document.getElementById('submitRev');if(btn){btn.disabled=true;btn.style.opacity='0.6'}try{await postReview(review);msg.className='text-center text-sm text-emerald-400';msg.textContent=existing?'Review updated.':'Thanks — your review is live.';msg.classList.remove('hidden');setTimeout(()=>msg.classList.add('hidden'),2500);renderReviews(reviewsCache)}catch(e){msg.className='text-center text-sm text-amber-400';msg.textContent=e.message;msg.classList.remove('hidden')}if(btn){btn.disabled=false;btn.style.opacity='1'}});
document.getElementById('deleteMyRev')?.addEventListener('click',async()=>{const mine=myReview();if(!mine)return;if(!confirm('Delete your review?'))return;const msg=document.getElementById('revMsg');try{await deleteReview(mine.id);setFormFromReview(null);msg.className='text-center text-sm text-emerald-400';msg.textContent='Review deleted.';msg.classList.remove('hidden');setTimeout(()=>msg.classList.add('hidden'),2500);renderReviews(reviewsCache)}catch(e){msg.className='text-center text-sm text-amber-400';msg.textContent=e.message;msg.classList.remove('hidden')}});

document.getElementById('adminWipeBtn')?.addEventListener('click',async()=>{
  const word=(document.getElementById('adminWord')?.value||'').trim();
  const msg=document.getElementById('adminMsg');
  if(!word){if(msg){msg.className='text-xs mt-2 text-amber-400';msg.textContent='Enter admin word';msg.classList.remove('hidden')}return}
  if(!confirm('Wipe ALL reviews and accounts? This cannot be undone (until cold start).'))return;
  try{
    const r=await fetch('/api/reviews',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({wipe:true,wipeUsers:true,adminWord:word})});
    const data=await r.json();
    if(!r.ok)throw new Error(data.error||'Wipe failed');
    reviewsCache=[];
    renderReviews([]);
    if(msg){msg.className='text-xs mt-2 text-emerald-400';msg.textContent='Wiped all reviews and users.';msg.classList.remove('hidden')}
    document.getElementById('adminWord').value='';
  }catch(e){if(msg){msg.className='text-xs mt-2 text-amber-400';msg.textContent=e.message;msg.classList.remove('hidden')}}
});

(async()=>{await loadUser();buildScoreBtns();await fetchReviews();renderReviews(reviewsCache)})();
